apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: blackbox-exporter
  namespace: monitoring
spec:
  interval: 30m
  dependsOn:
    - name: victoria-metrics-k8s-stack
      namespace: monitoring
  chart:
    spec:
      chart: prometheus-blackbox-exporter
      version: "8.17.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: monitoring
  values:
    fullnameOverride: blackbox-exporter
    config:
      modules:
        http_2xx:
          prober: http
          http:
            preferred_ip_protocol: ip4
            valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
            valid_status_codes: [200]
            method: GET
        icmp:
          prober: icmp
          icmp:
            preferred_ip_protocol: ip4
    service:
      type: ClusterIP
      port: 9115
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "100m"
