apiVersion: ENC[AES256_GCM,data:sGQ=,iv:wI38kmqlYateCDBPtxhHjT0jkHqdviOoZVGWraOlQgU=,tag:7E5PR1vINVsD2a0QJF+Jjg==,type:str]
kind: ENC[AES256_GCM,data:UhFRbL6U,iv:NC80tAk0fAAUvkKBlwEgYorJCT5mRKPdQPIjI3sX+bw=,tag:S5JhvqOE5D6hWku/5kyXaQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:jWsJNhyL7PPwqVFqlQ==,iv:0efLTJ6p7o073QdfrbnYgL8aXVTmTWzHX6hJXs3k3EY=,tag:IsES4NretvU82GdiJMUL1A==,type:str]
    namespace: ENC[AES256_GCM,data:r1ZCxrZSEE2nbA==,iv:sqUMC5PZS0Mv+su22oO0Q7otoe7Bp5AnELAlkZUCHug=,tag:KCw3Whr0sO7I9S6T1x1a5Q==,type:str]
type: ENC[AES256_GCM,data:kHgRSuFd,iv:29NwmimOh2foKXoPDUBw96cFh6GorrBsgu7o8cXEyuM=,tag:ObKY5LQQi8BwcLuamGk+JA==,type:str]
stringData:
    admin-user: ENC[AES256_GCM,data:x0iSGmw=,iv:jpNG3beS1+CZV6T0D99zfZuX7AFdo9huJVIhl7UqsyU=,tag:KOMX0Ygo8+ZfTz8PixX2Ng==,type:str]
    admin-password: ENC[AES256_GCM,data:pXXBRPdRww8h8tpH6Q45IES2puk=,iv:KYpCFFLGZ/b/WeKxc+Pw+WKHX0yAzKIeWooOc83gulw=,tag:7so44rkQn7DyZtr7YF7/Hw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fjpzfukaht4c2z2xnsj6k6ghny2tg9m20a8n0anjj9hyk8sxh3msuamjhc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFQ1hqYThYZDBML3ZVaGh3
            YWQ4VWE4amtHckJtYkJMNmJ0dlZVUHBEejJBCi9YdVI1RC9YTkJ0bTlCeGowMXRv
            WitiRUhxdE5iM2hDbTRRR1FPZmIvUUUKLS0tIG1aU0o1NVdkZUp6ZGZUQXpkbUNt
            OTBYdG1VZ2JYdG1XNE9BOXpJQnVrOTQKm0u1DdYbODd6Ls/5NbB0ikURGhsKbOaO
            xwMWaM+iWdDLmVFR7umbYolOTWwbHWKUYN9u6KLeMGS6KQSlqoOJRA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-24T19:39:51Z"
    mac: ENC[AES256_GCM,data:sUIbp4Y9VJNnsv7NIddnctP7RXHmUKeUnFm+/BNX7pGx+5Ik9d/Y66/+UEcokyXP7nk+QVyOpAIxXRgbBAh5m7Sa0YQ63le9OHAz+c1/1y3AxZGv5HnQfldPI3b8Ug/4mY4Bkj8+Spa7iM5FlGPG/MN48oD+HzaeGt3nZea8hLg=,iv:3qlt+PnlEWJ25p6+0NMvKPK2T38SpUxagDykcV7aaSQ=,tag:Ksah7uu21g+MOe24C4XOQQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
