apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kube-state-metrics
  namespace: monitoring
spec:
  interval: 24h
  url: https://kubernetes.github.io/kube-state-metrics
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-state-metrics
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: kube-state-metrics
      version: "5.27.0"
      sourceRef:
        kind: HelmRepository
        name: kube-state-metrics
        namespace: monitoring
  values:
    service:
      type: ClusterIP
      port: 8080
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "100m"