apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-config-custom
  namespace: monitoring
data:
  telegraf.conf: |
    # Global tags
    [global_tags]
      environment = "homelab"
      cluster = "home1"

    # Agent configuration
    [agent]
      interval = "10s"
      round_interval = true
      metric_batch_size = 1000
      metric_buffer_limit = 10000
      collection_jitter = "0s"
      flush_interval = "10s"
      flush_jitter = "0s"
      precision = ""
      hostname = ""
      omit_hostname = false

    # OUTPUT PLUGINS
    [[outputs.http]]
      url = "http://victoriametrics-victoria-metrics-single-server:8428/api/v1/write"
      data_format = "prometheusremotewrite"
      [outputs.http.headers]
        Content-Type = "application/x-protobuf"
        Content-Encoding = "snappy"
        X-Prometheus-Remote-Write-Version = "0.1.0"

    # System metrics
    [[inputs.cpu]]
      percpu = true
      totalcpu = true
      collect_cpu_time = false
      report_active = false

    [[inputs.disk]]
      ignore_fs = ["tmpfs", "devtmpfs", "devfs", "iso9660", "overlay", "aufs", "squashfs"]

    [[inputs.diskio]]

    [[inputs.mem]]

    [[inputs.processes]]

    [[inputs.system]]

    [[inputs.net]]

    # HTTP response checks for services
    [[inputs.http_response]]
      urls = [
        "http://jellyfin.jellyfin.svc.cluster.local:8096/health",
        "http://home-assistant.home-assistant.svc.cluster.local:8123/api/",
        "http://grafana:80/api/health"
      ]
      response_timeout = "5s"
      method = "GET"
      follow_redirects = false

    # DNS monitoring
    [[inputs.dns_query]]
      servers = ["8.8.8.8", "1.1.1.1"]
      domains = ["google.com", "lab.lkwt.dev"]
      record_type = "A"
      port = 53
      timeout = 2

    # Ping tests
    [[inputs.ping]]
      urls = ["8.8.8.8", "192.168.68.1"]
      count = 1
      deadline = 10
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf-custom
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegraf-custom
  template:
    metadata:
      labels:
        app: telegraf-custom
    spec:
      containers:
      - name: telegraf
        image: telegraf:1.28-alpine
        volumeMounts:
        - name: config
          mountPath: /etc/telegraf
        - name: docker-socket
          mountPath: /var/run/docker.sock
          readOnly: true
        - name: proc
          mountPath: /host/proc
          readOnly: true
        - name: sys
          mountPath: /host/sys
          readOnly: true
        env:
        - name: HOST_PROC
          value: "/host/proc"
        - name: HOST_SYS
          value: "/host/sys"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: config
        configMap:
          name: telegraf-config-custom
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock
      - name: proc
        hostPath:
          path: /proc
      - name: sys
        hostPath:
          path: /sys
      hostNetwork: false
      hostPID: false