apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-repositories.yaml
  - cert-manager.yaml
  - cert-manager-config.yaml
  - external-dns.yaml
  - nginx-gateway.yaml
  - tailscale.yaml
