apiVersion: ENC[AES256_GCM,data:K88=,iv:pS9yfqfEvASSrr8HGPsrhuIWPoYCOXafROLhaIXWwAI=,tag:xKgSt3n5cnTh8hWUB/QjOA==,type:str]
kind: ENC[AES256_GCM,data:tYwJ041j,iv:+vRl1FDU97oOTRvUBgFr7P/H8l25m+hPEbC+LaGgARU=,tag:RT84YE8KOOO7TilIEz1A9Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:gf6wfDXajg==,iv:sLZ8QyXlySg1DFkk/mGO/naNJlDCcIrYpxuLGUiSWio=,tag:m49UIb84By0Iuki9axdwKw==,type:str]
    namespace: ENC[AES256_GCM,data:B/tISPqYOg==,iv:kaJPhXo4zQfauilkw3OIygVjWLxfP20d+KfAuM72Ehs=,tag:i/D/KFI7pnEjmzJTwq1Omg==,type:str]
type: ENC[AES256_GCM,data:Rsg+cZlp,iv:CG1gP7LisGnAdKq5OD0y+AgzUfEfjagPZidb+CwL58k=,tag:Xy1keJa5wgWvBQ3XpGV5Ng==,type:str]
stringData:
    secret-key: ENC[AES256_GCM,data:F8KEp/ZRtWNrkRFUoWoLhm09klBxUTSto3eZrrsScSKzqEsqlvSaWZo4j5UcCMaq7HvO2RbZjEPlPAZV5U69wA==,iv:gAT3Ah8j3+cNurcB2mwUy+ATZcEY/V9EZbHkd0KVJ0w=,tag:DAD2FPp1XOxS72cxMCiUPg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fjpzfukaht4c2z2xnsj6k6ghny2tg9m20a8n0anjj9hyk8sxh3msuamjhc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsaHlQdWVyNDQ5cTlPWldM
            WUU1eXppbmFjeGdsbnFSVDBIMndKMW9IbkQwCmRBUURwUlYwdlRXMitDL1BVZnVU
            ZC8vRFVoTDN4REZDYnJRNENKdFh5ODQKLS0tIDZtUXVVVkFkT21zM3hDbjFOaVRI
            T3RuWUw3RWtpWGJ2cWpVN3FJSTRTUm8Km5UjyRqyRjZshxNAYzyceTrFEHYvGOdz
            aqiX+CHTe3QBASWQeeCTdJ5annmRgqpqQ+rfeVtpix8kbIy0RUOYNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-24T19:39:51Z"
    mac: ENC[AES256_GCM,data:CkLMFZoVNakleMGD+x6Nr8c5aChYrcRK+543jZ9TUQ9UjMwy8iQHUmvTqeAjKrofSSU735d0Z1nRExTdQE1GeA9B1OoanqiieCDTVpioHWuVB7p1TF8dF9uAbZpOEseT4xZS11YS1vKQSXH5YRMzc1GTgF28pit34807Fa8jl6g=,iv:0stnkSzSf1AjS6DMWR5gTIcl4C3LSLV9fBecxAUf2NQ=,tag:lU8UPWGFjJzUxXBlun1Nrw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
