---
apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 30m
  ref:
    tag: v0.13.12
  url: https://github.com/metallb/metallb
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-system
  namespace: flux-system
spec:
  interval: 10m
  path: "./config/default"
  prune: true
  sourceRef:
    kind: GitRepository
    name: metallb
  targetNamespace: metallb-system
  wait: true