apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx-gateway-fabric
  namespace: nginx-gateway
spec:
  interval: 10m
  chart:
    spec:
      chart: nginx-gateway-fabric
      version: "1.2.0"
      sourceRef:
        kind: HelmRepository
        name: nginx-gateway-fabric
  values:
    service:
      type: NodePort
