apiVersion: v1
kind: Namespace
metadata:
  name: nginx-gateway
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx-gateway-fabric
  namespace: nginx-gateway
spec:
  interval: 10m
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
  chart:
    spec:
      chart: nginx-gateway-fabric
      version: "1.2.0"
      sourceRef:
        kind: HelmRepository
        name: nginx-gateway-fabric
        namespace: flux-system
  values:
    service:
      ports:
      - name: https
        port: 443
        protocol: TCP
        targetPort: 443

    # Fix restart issues with Unix socket binding
    nginx:
      lifecycle:
        preStop:
          exec:
            command:
            - /bin/sh
            - -c
            - "nginx -s quit; sleep 5"

    # Add restart policy and probe configuration
    deployment:
      replicas: 1
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: 0
          maxSurge: 1

    # Configure probes to detect socket binding issues
    nginxGateway:
      readinessProbe:
        initialDelaySeconds: 10
        periodSeconds: 5
        timeoutSeconds: 3
        failureThreshold: 6
      livenessProbe:
        initialDelaySeconds: 30
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 3

    # Ensure proper cleanup of Unix sockets
    initContainers:
      - name: socket-cleanup
        image: busybox:1.35
        command:
        - /bin/sh
        - -c
        - |
          echo "Cleaning up any existing Unix sockets..."
          rm -f /var/lib/nginx/*.sock /var/run/nginx/*.sock || true
          echo "Socket cleanup complete"
        volumeMounts:
        - name: nginx-lib
          mountPath: /var/lib/nginx
        - name: nginx-run
          mountPath: /var/run/nginx

    # Add volume mounts for socket directories
    extraVolumes:
      - name: nginx-lib
        emptyDir: {}
      - name: nginx-run
        emptyDir: {}

    extraVolumeMounts:
      - name: nginx-lib
        mountPath: /var/lib/nginx
      - name: nginx-run
        mountPath: /var/run/nginx
