apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-lab-lkwt-dev
  namespace: cert-manager
spec:
  secretName: wildcard-lab-lkwt-dev-tls
  dnsNames:
    - '*.lab.lkwt.dev'
  issuerRef:
    name: letsencrypt-wildcard
    kind: ClusterIssuer
