apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-wildcard
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: luke@lkwt.dev
    privateKeySecretRef:
      name: letsencrypt-wildcard-key
    solvers:
      - dns01:
          cloudflare:
            email: luke@lukewiltshire.co.uk
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-lab-lkwt-dev
  namespace: nginx-gateway
spec:
  secretName: wildcard-lab-lkwt-dev-tls
  dnsNames:
    - '*.lab.lkwt.dev'
  issuerRef:
    name: letsencrypt-wildcard
    kind: ClusterIssuer

