apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: open-8gears
  namespace: n8n
spec:
  interval: 24h
  type: oci
  url: oci://8gears.container-registry.com/library
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitnami
  namespace: n8n
spec:
  interval: 24h
  url: https://charts.bitnami.com/bitnami
