apiVersion: v1
kind: Secret
metadata:
  name: n8n-secrets
  namespace: n8n
type: Opaque
stringData:
  N8N_ENCRYPTION_KEY: "b36f66f17dba5a14a6f270ea0e091f677b348afb212ffdff1309ce8a076bec91"
  DB_POSTGRESDB_PASSWORD: "4b528891fe775f8b355b3859301170b2"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-credentials
  namespace: n8n
type: Opaque
stringData:
  postgres-password: "4b528891fe775f8b355b3859301170b2"
