apiVersion: ENC[AES256_GCM,data:9UA=,iv:fz/iewZrsMfnqDJ9RWRtSXfMCnsFZmPK2OoTdpkFoH8=,tag:Y1oClZ6QUOS/XC670aEu/Q==,type:str]
kind: ENC[AES256_GCM,data:NWJwFdXG,iv:vHS0VeomyidH9x8e3ofnptvqMgb3HXHV1kHZPRyWGzE=,tag:XdtnIQm6witN43Al5nwVBg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:2OQweCdT8CRfIno=,iv:EFb1KZtaFPW+8vxZJqO2XW8DRH8444jY7LoFIMIbdK4=,tag:J89QJzv3nfQNY2EZ7QSjig==,type:str]
    namespace: ENC[AES256_GCM,data:LHPB,iv:njfBN+JI7mOsAdD6yl1Ty0ukqLdLPO/faoyW80QHzUo=,tag:lKFJJuN/fQJmlQzhNfxVZQ==,type:str]
type: ENC[AES256_GCM,data:hLznfjAS,iv:3S7cDapOWvNtmBw2spCYNlV6hBFvOorpJ+OX7880eQ0=,tag:ZoFMCdMSsVifoOlwR6DEPw==,type:str]
stringData:
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:5M0d5pMGEsPkpQRDEHvU7l674bqDe1aOSjBleKHarcAg9qzs4HqixaqE7IZLqKgaFeujlDlZCguY9/rqEcCsEQ==,iv:DjqcfUcH/sOh1p0WSOuEURQYClFjdCpTF9YW2P2KBRc=,tag:a9XaO3+p943cpx+dhvfUcQ==,type:str]
    DB_POSTGRESDB_PASSWORD: ENC[AES256_GCM,data:osAPuWU5ddCKVjKc6237LYYr20bAJCULABmAEVV2dks=,iv:nV8KmbgFWbWMTf32rbI/bNjkZmm///IM6cIlzqU/MLU=,tag:jHopIa9wcsnVY28nxUJutw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fjpzfukaht4c2z2xnsj6k6ghny2tg9m20a8n0anjj9hyk8sxh3msuamjhc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWNllNeHh4QmwzRGVrZUk4
            VEk5MEJ0VzhUOHVaamdZQUY4ZVQ3L2t2cFZnCkExRUlneVpNNjZiSXdTOUlwaXZm
            cUFTb0hrbThKeWgxSnZiWWdJTFJVUVEKLS0tIEdJMHdCWWtONVdXM3NPQWVEMXFy
            SzRnTVlLRjdBamoyOWJsck0vWURDZUkKTMLagxNg8dMzBVfyCBVm1vcqcRmaFFGL
            ueV9iiF9MEr9FB3Sew/41Ul48bLqa1XGe/z3IsDRQJw81ITNZHRH8g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-24T19:39:45Z"
    mac: ENC[AES256_GCM,data:xhf2ZQtCkPiXHu385r0hIy97oHaCObpqOAIu/nBcBUYF044sXaLuqHvIqCTIJR2leYrImOCaAC2iRdeg1CtTK2Oi8+RsWsBHHikl1euESIqiO6vEOthHF2ld1R2AP8RSC9YoavGUHG9I+I6gEDdSduBKa/vRNoEbilw9eo0c5S0=,iv:BzIjnorzrelY65z4LDGafqUU0YDPlaeIc7I/IQrgC/A=,tag:a4IJSsRrXW4WMCOMycy5UQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
